package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"go.infratographer.com/instance-api/internal/ent"
)

// FindInstanceByID is the resolver for the findInstanceByID field.
func (r *entityResolver) FindInstanceByID(ctx context.Context, id uuid.UUID) (*ent.Instance, error) {
	panic(fmt.Errorf("not implemented: FindInstanceByID - findInstanceByID"))
}

// FindInstanceMetadataByID is the resolver for the findInstanceMetadataByID field.
func (r *entityResolver) FindInstanceMetadataByID(ctx context.Context, id uuid.UUID) (*ent.InstanceMetadata, error) {
	panic(fmt.Errorf("not implemented: FindInstanceMetadataByID - findInstanceMetadataByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
