package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/internal/ent/generated"
)

// CreateInstanceProvider is the resolver for the createInstanceProvider field.
func (r *mutationResolver) CreateInstanceProvider(ctx context.Context, input generated.CreateInstanceProviderInput) (*generated.InstanceProvider, error) {
	panic(fmt.Errorf("not implemented: CreateInstanceProvider - createInstanceProvider"))
}

// UpdateInstanceProvider is the resolver for the updateInstanceProvider field.
func (r *mutationResolver) UpdateInstanceProvider(ctx context.Context, input generated.UpdateInstanceProviderInput) (*generated.InstanceProvider, error) {
	panic(fmt.Errorf("not implemented: UpdateInstanceProvider - updateInstanceProvider"))
}
