package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/instance-api/internal/ent/generated"
	"go.infratographer.com/instance-api/internal/ent/generated/instance"
	graphapigen "go.infratographer.com/instance-api/internal/graphapi/generated"
	"go.infratographer.com/x/gidx"
)

// Location is the resolver for the location field.
func (r *instanceResolver) Location(ctx context.Context, obj *generated.Instance) (*graphapigen.Location, error) {
	return &graphapigen.Location{ID: obj.LocationID}, nil
}

// Instances is the resolver for the instances field.
func (r *locationResolver) Instances(ctx context.Context, obj *graphapigen.Location, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.InstanceOrder, where *generated.InstanceWhereInput) (*generated.InstanceConnection, error) {
	return r.client.Instance.Query().Where(instance.LocationID(obj.ID)).Paginate(ctx, after, first, before, last, generated.WithInstanceOrder(orderBy), generated.WithInstanceFilter(where.Filter))
}

// Location returns graphapigen.LocationResolver implementation.
func (r *Resolver) Location() graphapigen.LocationResolver { return &locationResolver{r} }

type locationResolver struct{ *Resolver }
