// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"github.com/google/uuid"
	"go.infratographer.com/instance-api/internal/ent"
)

type Tenant struct {
	ID        uuid.UUID               `json:"id"`
	Instances *ent.InstanceConnection `json:"instances"`
}
