package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
	"go.infratographer.com/instance-api/internal/ent"
)

// Instances is the resolver for the instances field.
func (r *tenantResolver) Instances(ctx context.Context, obj *Tenant, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy *ent.InstanceOrder) (*ent.InstanceConnection, error) {
	panic(fmt.Errorf("not implemented: Instances - instances"))
}

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

type tenantResolver struct{ *Resolver }
