// Copyright 2022 The Infratographer Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"go.infratographer.com/instance-api/internal/ent/instance"
	"go.infratographer.com/instance-api/internal/ent/instancemetadata"
	"go.infratographer.com/instance-api/internal/ent/instanceprovider"
	"go.infratographer.com/instance-api/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescName is the schema descriptor for name field.
	instanceDescName := instanceFields[1].Descriptor()
	// instance.NameValidator is a validator for the "name" field. It is called by the builders before save.
	instance.NameValidator = instanceDescName.Validators[0].(func(string) error)
	// instanceDescCreatedAt is the schema descriptor for created_at field.
	instanceDescCreatedAt := instanceFields[2].Descriptor()
	// instance.DefaultCreatedAt holds the default value on creation for the created_at field.
	instance.DefaultCreatedAt = instanceDescCreatedAt.Default.(func() time.Time)
	// instanceDescUpdatedAt is the schema descriptor for updated_at field.
	instanceDescUpdatedAt := instanceFields[3].Descriptor()
	// instance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instance.DefaultUpdatedAt = instanceDescUpdatedAt.Default.(func() time.Time)
	// instance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instance.UpdateDefaultUpdatedAt = instanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// instanceDescID is the schema descriptor for id field.
	instanceDescID := instanceFields[0].Descriptor()
	// instance.DefaultID holds the default value on creation for the id field.
	instance.DefaultID = instanceDescID.Default.(func() uuid.UUID)
	instancemetadataFields := schema.InstanceMetadata{}.Fields()
	_ = instancemetadataFields
	// instancemetadataDescNamespace is the schema descriptor for namespace field.
	instancemetadataDescNamespace := instancemetadataFields[1].Descriptor()
	// instancemetadata.NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	instancemetadata.NamespaceValidator = instancemetadataDescNamespace.Validators[0].(func(string) error)
	// instancemetadataDescCreatedAt is the schema descriptor for created_at field.
	instancemetadataDescCreatedAt := instancemetadataFields[3].Descriptor()
	// instancemetadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	instancemetadata.DefaultCreatedAt = instancemetadataDescCreatedAt.Default.(func() time.Time)
	// instancemetadataDescUpdatedAt is the schema descriptor for updated_at field.
	instancemetadataDescUpdatedAt := instancemetadataFields[4].Descriptor()
	// instancemetadata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instancemetadata.DefaultUpdatedAt = instancemetadataDescUpdatedAt.Default.(func() time.Time)
	// instancemetadata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instancemetadata.UpdateDefaultUpdatedAt = instancemetadataDescUpdatedAt.UpdateDefault.(func() time.Time)
	// instancemetadataDescID is the schema descriptor for id field.
	instancemetadataDescID := instancemetadataFields[0].Descriptor()
	// instancemetadata.DefaultID holds the default value on creation for the id field.
	instancemetadata.DefaultID = instancemetadataDescID.Default.(func() uuid.UUID)
	instanceproviderFields := schema.InstanceProvider{}.Fields()
	_ = instanceproviderFields
	// instanceproviderDescName is the schema descriptor for name field.
	instanceproviderDescName := instanceproviderFields[1].Descriptor()
	// instanceprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	instanceprovider.NameValidator = instanceproviderDescName.Validators[0].(func(string) error)
	// instanceproviderDescCreatedAt is the schema descriptor for created_at field.
	instanceproviderDescCreatedAt := instanceproviderFields[2].Descriptor()
	// instanceprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	instanceprovider.DefaultCreatedAt = instanceproviderDescCreatedAt.Default.(func() time.Time)
	// instanceproviderDescUpdatedAt is the schema descriptor for updated_at field.
	instanceproviderDescUpdatedAt := instanceproviderFields[3].Descriptor()
	// instanceprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instanceprovider.DefaultUpdatedAt = instanceproviderDescUpdatedAt.Default.(func() time.Time)
	// instanceprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instanceprovider.UpdateDefaultUpdatedAt = instanceproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// instanceproviderDescID is the schema descriptor for id field.
	instanceproviderDescID := instanceproviderFields[0].Descriptor()
	// instanceprovider.DefaultID holds the default value on creation for the id field.
	instanceprovider.DefaultID = instanceproviderDescID.Default.(func() uuid.UUID)
}
