// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

func testInstanceProvidersUpsert(t *testing.T) {
	t.Parallel()

	if len(instanceProviderAllColumns) == len(instanceProviderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := InstanceProvider{}
	if err = randomize.Struct(seed, &o, instanceProviderDBTypes, true); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InstanceProvider: %s", err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, instanceProviderDBTypes, false, instanceProviderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InstanceProvider: %s", err)
	}

	count, err = InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testInstanceProviders(t *testing.T) {
	t.Parallel()

	query := InstanceProviders()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testInstanceProvidersSoftDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersQuerySoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := InstanceProviders().DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersSliceSoftDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InstanceProviderSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, false); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := InstanceProviders().DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InstanceProviderSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx, true); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceProvidersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := InstanceProviderExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if InstanceProvider exists: %s", err)
	}
	if !e {
		t.Errorf("Expected InstanceProviderExists to return true, but got false.")
	}
}

func testInstanceProvidersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	instanceProviderFound, err := FindInstanceProvider(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if instanceProviderFound == nil {
		t.Error("want a record, got nil")
	}
}

func testInstanceProvidersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = InstanceProviders().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testInstanceProvidersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := InstanceProviders().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testInstanceProvidersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	instanceProviderOne := &InstanceProvider{}
	instanceProviderTwo := &InstanceProvider{}
	if err = randomize.Struct(seed, instanceProviderOne, instanceProviderDBTypes, false, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}
	if err = randomize.Struct(seed, instanceProviderTwo, instanceProviderDBTypes, false, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = instanceProviderOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = instanceProviderTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InstanceProviders().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testInstanceProvidersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	instanceProviderOne := &InstanceProvider{}
	instanceProviderTwo := &InstanceProvider{}
	if err = randomize.Struct(seed, instanceProviderOne, instanceProviderDBTypes, false, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}
	if err = randomize.Struct(seed, instanceProviderTwo, instanceProviderDBTypes, false, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = instanceProviderOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = instanceProviderTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func instanceProviderBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func instanceProviderAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceProvider) error {
	*o = InstanceProvider{}
	return nil
}

func testInstanceProvidersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &InstanceProvider{}
	o := &InstanceProvider{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, false); err != nil {
		t.Errorf("Unable to randomize InstanceProvider object: %s", err)
	}

	AddInstanceProviderHook(boil.BeforeInsertHook, instanceProviderBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	instanceProviderBeforeInsertHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.AfterInsertHook, instanceProviderAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	instanceProviderAfterInsertHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.AfterSelectHook, instanceProviderAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	instanceProviderAfterSelectHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.BeforeUpdateHook, instanceProviderBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	instanceProviderBeforeUpdateHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.AfterUpdateHook, instanceProviderAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	instanceProviderAfterUpdateHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.BeforeDeleteHook, instanceProviderBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	instanceProviderBeforeDeleteHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.AfterDeleteHook, instanceProviderAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	instanceProviderAfterDeleteHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.BeforeUpsertHook, instanceProviderBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	instanceProviderBeforeUpsertHooks = []InstanceProviderHook{}

	AddInstanceProviderHook(boil.AfterUpsertHook, instanceProviderAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	instanceProviderAfterUpsertHooks = []InstanceProviderHook{}
}

func testInstanceProvidersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInstanceProvidersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(instanceProviderColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInstanceProviderToManyInstances(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a InstanceProvider
	var b, c Instance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, instanceDBTypes, false, instanceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, instanceDBTypes, false, instanceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.InstanceProviderID = a.ID
	c.InstanceProviderID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Instances().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.InstanceProviderID == b.InstanceProviderID {
			bFound = true
		}
		if v.InstanceProviderID == c.InstanceProviderID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := InstanceProviderSlice{&a}
	if err = a.L.LoadInstances(ctx, tx, false, (*[]*InstanceProvider)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Instances); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Instances = nil
	if err = a.L.LoadInstances(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Instances); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testInstanceProviderToManyAddOpInstances(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a InstanceProvider
	var b, c, d, e Instance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, instanceProviderDBTypes, false, strmangle.SetComplement(instanceProviderPrimaryKeyColumns, instanceProviderColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Instance{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, instanceDBTypes, false, strmangle.SetComplement(instancePrimaryKeyColumns, instanceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Instance{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddInstances(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.InstanceProviderID {
			t.Error("foreign key was wrong value", a.ID, first.InstanceProviderID)
		}
		if a.ID != second.InstanceProviderID {
			t.Error("foreign key was wrong value", a.ID, second.InstanceProviderID)
		}

		if first.R.InstanceProvider != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.InstanceProvider != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Instances[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Instances[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Instances().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testInstanceProvidersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInstanceProvidersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InstanceProviderSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInstanceProvidersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InstanceProviders().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	instanceProviderDBTypes = map[string]string{`ID`: `uuid`, `Name`: `string`, `TenantID`: `uuid`, `CreatedAt`: `timestamptz`, `UpdatedAt`: `timestamptz`, `DeletedAt`: `timestamptz`}
	_                       = bytes.MinRead
)

func testInstanceProvidersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(instanceProviderPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(instanceProviderAllColumns) == len(instanceProviderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testInstanceProvidersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(instanceProviderAllColumns) == len(instanceProviderPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InstanceProvider{}
	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceProviders().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, instanceProviderDBTypes, true, instanceProviderPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceProvider struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(instanceProviderAllColumns, instanceProviderPrimaryKeyColumns) {
		fields = instanceProviderAllColumns
	} else {
		fields = strmangle.SetComplement(
			instanceProviderAllColumns,
			instanceProviderPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := InstanceProviderSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
