// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/nrfta/go-paging"
)

type Node interface {
	IsNode()
	GetID() string
}

type CreateInstanceInput struct {
	Name       string `json:"name"`
	LocationID string `json:"locationId"`
	TenantID   string `json:"tenantId"`
	ProviderID string `json:"providerId"`
}

type CreateInstanceProviderInput struct {
	Name     string `json:"name"`
	TenantID string `json:"tenantId"`
}

type Instance struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Tenant    *Tenant           `json:"tenant"`
	Location  *Location         `json:"location"`
	Provider  *InstanceProvider `json:"provider"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
	DeletedAt *time.Time        `json:"deletedAt,omitempty"`
}

func (Instance) IsNode()            {}
func (this Instance) GetID() string { return this.ID }

func (Instance) IsEntity() {}

type InstanceConnection struct {
	Edges      []*InstanceEdge  `json:"edges"`
	Nodes      []*Instance      `json:"nodes"`
	PageInfo   *paging.PageInfo `json:"pageInfo"`
	TotalCount int              `json:"totalCount"`
}

type InstanceEdge struct {
	Cursor *string   `json:"cursor,omitempty"`
	Node   *Instance `json:"node,omitempty"`
}

type InstanceProvider struct {
	ID        string              `json:"id"`
	Name      string              `json:"name"`
	Tenant    *Tenant             `json:"tenant"`
	CreatedAt time.Time           `json:"createdAt"`
	UpdatedAt time.Time           `json:"updatedAt"`
	DeletedAt *time.Time          `json:"deletedAt,omitempty"`
	Instances *InstanceConnection `json:"instances,omitempty"`
}

type Location struct {
	ID        string              `json:"id"`
	Instances *InstanceConnection `json:"instances"`
}

type Tenant struct {
	ID        string              `json:"id"`
	Instances *InstanceConnection `json:"instances"`
}

type UpdateInstanceInput struct {
	Name string `json:"name"`
}

type UpdateInstanceProviderInput struct {
	Name string `json:"name"`
}
