package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/graph"
)

// FindInstanceByID is the resolver for the findInstanceByID field.
func (r *entityResolver) FindInstanceByID(ctx context.Context, id string) (*graph.Instance, error) {
	panic(fmt.Errorf("not implemented: FindInstanceByID - findInstanceByID"))
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
