package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/graph"
)

// Instances is the resolver for the instances field.
func (r *queryResolver) Instances(ctx context.Context) (*graph.InstanceConnection, error) {
	return loadInstances(ctx, nil, r.db)
}

// InstanceProviders is the resolver for the instanceProviders field.
func (r *queryResolver) InstanceProviders(ctx context.Context) ([]*graph.InstanceProvider, error) {
	panic(fmt.Errorf("not implemented: InstanceProviders - instanceProviders"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
