package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"go.infratographer.com/instance-api/graph"
	"go.infratographer.com/instance-api/internal/models"
)

// Instance is the resolver for the instance field.
func (r *queryResolver) Instance(ctx context.Context, id string) (*graph.Instance, error) {
	instance, err := models.FindInstance(ctx, r.db, id)
	if err != nil {
		return nil, err
	}

	res := &graph.Instance{
		ID:       instance.ID,
		Name:     instance.Name,
		Location: &graph.Location{ID: instance.LocationID},
		Tenant:   &graph.Tenant{ID: instance.TenantID},
		Provider: &graph.InstanceProvider{ID: instance.InstanceProviderID},
	}

	return res, nil
}
