package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/graph"
)

// CreateInstance is the resolver for the createInstance field.
func (r *mutationResolver) CreateInstance(ctx context.Context, input graph.CreateInstanceInput) (*graph.Instance, error) {
	panic(fmt.Errorf("not implemented: CreateInstance - createInstance"))
}

// UpdateInstance is the resolver for the updateInstance field.
func (r *mutationResolver) UpdateInstance(ctx context.Context, input graph.UpdateInstanceInput) (*graph.Instance, error) {
	panic(fmt.Errorf("not implemented: UpdateInstance - updateInstance"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
