package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/graph"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (graph.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}
