package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"go.infratographer.com/instance-api/graph"
)

// InstanceProvider is the resolver for the instanceProvider field.
func (r *queryResolver) InstanceProvider(ctx context.Context, id string) (*graph.InstanceProvider, error) {
	panic(fmt.Errorf("not implemented: InstanceProvider - instanceProvider"))
}
